export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRY_DETAIL = "GET_COUNTRY_DETAIL";
export const GET_NAMES = "GET_NAMES";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const CLEAR_COUNTRY_DETAIL = "CLEAR_COUNTRY_DETAIL";
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
